/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Hentu.Demo.Service.Thrift
{
  /// <summary>
  /// Demo枚举 用户性别
  /// </summary>
  public enum EnumUserSex
  {
    /// <summary>
    /// 男
    /// </summary>
    Man = 0,
    /// <summary>
    /// 女
    /// </summary>
    Woman = 1,
    /// <summary>
    /// 未知
    /// </summary>
    Unknown = 2,
  }
}
