/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hentu.Demo.Service.Thrift
{
  public partial class HentuDemoService {
    public interface Iface {
      /// <summary>
      /// Demo类 用户 添加
      /// @param user 用户
      /// </summary>
      /// <param name="user"></param>
      bool DemoUser_Add(DemoUser user);
      #if SILVERLIGHT
      IAsyncResult Begin_DemoUser_Add(AsyncCallback callback, object state, DemoUser user);
      bool End_DemoUser_Add(IAsyncResult asyncResult);
      #endif
      /// <summary>
      /// Demo类 获取批量用户
      /// </summary>
      List<DemoUser> DemoUser_GetList();
      #if SILVERLIGHT
      IAsyncResult Begin_DemoUser_GetList(AsyncCallback callback, object state, );
      List<DemoUser> End_DemoUser_GetList(IAsyncResult asyncResult);
      #endif
    }

    public class Client : Iface {
      public Client(TProtocol prot) : this(prot, prot)
      {
      }

      public Client(TProtocol iprot, TProtocol oprot)
      {
        iprot_ = iprot;
        oprot_ = oprot;
      }

      protected TProtocol iprot_;
      protected TProtocol oprot_;
      protected int seqid_;

      public TProtocol InputProtocol
      {
        get { return iprot_; }
      }
      public TProtocol OutputProtocol
      {
        get { return oprot_; }
      }


      
      #if SILVERLIGHT
      public IAsyncResult Begin_DemoUser_Add(AsyncCallback callback, object state, DemoUser user)
      {
        return send_DemoUser_Add(callback, state, user);
      }

      public bool End_DemoUser_Add(IAsyncResult asyncResult)
      {
        oprot_.Transport.EndFlush(asyncResult);
        return recv_DemoUser_Add();
      }

      #endif

      /// <summary>
      /// Demo类 用户 添加
      /// @param user 用户
      /// </summary>
      /// <param name="user"></param>
      public bool DemoUser_Add(DemoUser user)
      {
        #if !SILVERLIGHT
        send_DemoUser_Add(user);
        return recv_DemoUser_Add();

        #else
        var asyncResult = Begin_DemoUser_Add(null, null, user);
        return End_DemoUser_Add(asyncResult);

        #endif
      }
      #if SILVERLIGHT
      public IAsyncResult send_DemoUser_Add(AsyncCallback callback, object state, DemoUser user)
      #else
      public void send_DemoUser_Add(DemoUser user)
      #endif
      {
        oprot_.WriteMessageBegin(new TMessage("DemoUser_Add", TMessageType.Call, seqid_));
        DemoUser_Add_args args = new DemoUser_Add_args();
        args.User = user;
        args.Write(oprot_);
        oprot_.WriteMessageEnd();
        #if SILVERLIGHT
        return oprot_.Transport.BeginFlush(callback, state);
        #else
        oprot_.Transport.Flush();
        #endif
      }

      public bool recv_DemoUser_Add()
      {
        TMessage msg = iprot_.ReadMessageBegin();
        if (msg.Type == TMessageType.Exception) {
          TApplicationException x = TApplicationException.Read(iprot_);
          iprot_.ReadMessageEnd();
          throw x;
        }
        DemoUser_Add_result result = new DemoUser_Add_result();
        result.Read(iprot_);
        iprot_.ReadMessageEnd();
        if (result.__isset.success) {
          return result.Success;
        }
        throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "DemoUser_Add failed: unknown result");
      }

      
      #if SILVERLIGHT
      public IAsyncResult Begin_DemoUser_GetList(AsyncCallback callback, object state, )
      {
        return send_DemoUser_GetList(callback, state);
      }

      public List<DemoUser> End_DemoUser_GetList(IAsyncResult asyncResult)
      {
        oprot_.Transport.EndFlush(asyncResult);
        return recv_DemoUser_GetList();
      }

      #endif

      /// <summary>
      /// Demo类 获取批量用户
      /// </summary>
      public List<DemoUser> DemoUser_GetList()
      {
        #if !SILVERLIGHT
        send_DemoUser_GetList();
        return recv_DemoUser_GetList();

        #else
        var asyncResult = Begin_DemoUser_GetList(null, null, );
        return End_DemoUser_GetList(asyncResult);

        #endif
      }
      #if SILVERLIGHT
      public IAsyncResult send_DemoUser_GetList(AsyncCallback callback, object state, )
      #else
      public void send_DemoUser_GetList()
      #endif
      {
        oprot_.WriteMessageBegin(new TMessage("DemoUser_GetList", TMessageType.Call, seqid_));
        DemoUser_GetList_args args = new DemoUser_GetList_args();
        args.Write(oprot_);
        oprot_.WriteMessageEnd();
        #if SILVERLIGHT
        return oprot_.Transport.BeginFlush(callback, state);
        #else
        oprot_.Transport.Flush();
        #endif
      }

      public List<DemoUser> recv_DemoUser_GetList()
      {
        TMessage msg = iprot_.ReadMessageBegin();
        if (msg.Type == TMessageType.Exception) {
          TApplicationException x = TApplicationException.Read(iprot_);
          iprot_.ReadMessageEnd();
          throw x;
        }
        DemoUser_GetList_result result = new DemoUser_GetList_result();
        result.Read(iprot_);
        iprot_.ReadMessageEnd();
        if (result.__isset.success) {
          return result.Success;
        }
        throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "DemoUser_GetList failed: unknown result");
      }

    }
    public class Processor : TProcessor {
      public Processor(Iface iface)
      {
        iface_ = iface;
        processMap_["DemoUser_Add"] = DemoUser_Add_Process;
        processMap_["DemoUser_GetList"] = DemoUser_GetList_Process;
      }

      protected delegate void ProcessFunction(int seqid, TProtocol iprot, TProtocol oprot);
      private Iface iface_;
      protected Dictionary<string, ProcessFunction> processMap_ = new Dictionary<string, ProcessFunction>();

      public bool Process(TProtocol iprot, TProtocol oprot)
      {
        try
        {
          TMessage msg = iprot.ReadMessageBegin();
          ProcessFunction fn;
          processMap_.TryGetValue(msg.Name, out fn);
          if (fn == null) {
            TProtocolUtil.Skip(iprot, TType.Struct);
            iprot.ReadMessageEnd();
            TApplicationException x = new TApplicationException (TApplicationException.ExceptionType.UnknownMethod, "Invalid method name: '" + msg.Name + "'");
            oprot.WriteMessageBegin(new TMessage(msg.Name, TMessageType.Exception, msg.SeqID));
            x.Write(oprot);
            oprot.WriteMessageEnd();
            oprot.Transport.Flush();
            return true;
          }
          fn(msg.SeqID, iprot, oprot);
        }
        catch (IOException)
        {
          return false;
        }
        return true;
      }

      public void DemoUser_Add_Process(int seqid, TProtocol iprot, TProtocol oprot)
      {
        DemoUser_Add_args args = new DemoUser_Add_args();
        args.Read(iprot);
        iprot.ReadMessageEnd();
        DemoUser_Add_result result = new DemoUser_Add_result();
        result.Success = iface_.DemoUser_Add(args.User);
        oprot.WriteMessageBegin(new TMessage("DemoUser_Add", TMessageType.Reply, seqid)); 
        result.Write(oprot);
        oprot.WriteMessageEnd();
        oprot.Transport.Flush();
      }

      public void DemoUser_GetList_Process(int seqid, TProtocol iprot, TProtocol oprot)
      {
        DemoUser_GetList_args args = new DemoUser_GetList_args();
        args.Read(iprot);
        iprot.ReadMessageEnd();
        DemoUser_GetList_result result = new DemoUser_GetList_result();
        result.Success = iface_.DemoUser_GetList();
        oprot.WriteMessageBegin(new TMessage("DemoUser_GetList", TMessageType.Reply, seqid)); 
        result.Write(oprot);
        oprot.WriteMessageEnd();
        oprot.Transport.Flush();
      }

    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class DemoUser_Add_args : TBase
    {
      private DemoUser _user;

      public DemoUser User
      {
        get
        {
          return _user;
        }
        set
        {
          __isset.user = true;
          this._user = value;
        }
      }


      public Isset __isset;
      #if !SILVERLIGHT
      [Serializable]
      #endif
      public struct Isset {
        public bool user;
      }

      public DemoUser_Add_args() {
      }

      public void Read (TProtocol iprot)
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                User = new DemoUser();
                User.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }

      public void Write(TProtocol oprot) {
        TStruct struc = new TStruct("DemoUser_Add_args");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (User != null && __isset.user) {
          field.Name = "user";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          User.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }

      public override string ToString() {
        StringBuilder sb = new StringBuilder("DemoUser_Add_args(");
        sb.Append("User: ");
        sb.Append(User== null ? "<null>" : User.ToString());
        sb.Append(")");
        return sb.ToString();
      }

    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class DemoUser_Add_result : TBase
    {
      private bool _success;

      public bool Success
      {
        get
        {
          return _success;
        }
        set
        {
          __isset.success = true;
          this._success = value;
        }
      }


      public Isset __isset;
      #if !SILVERLIGHT
      [Serializable]
      #endif
      public struct Isset {
        public bool success;
      }

      public DemoUser_Add_result() {
      }

      public void Read (TProtocol iprot)
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 0:
              if (field.Type == TType.Bool) {
                Success = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }

      public void Write(TProtocol oprot) {
        TStruct struc = new TStruct("DemoUser_Add_result");
        oprot.WriteStructBegin(struc);
        TField field = new TField();

        if (this.__isset.success) {
          field.Name = "Success";
          field.Type = TType.Bool;
          field.ID = 0;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(Success);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }

      public override string ToString() {
        StringBuilder sb = new StringBuilder("DemoUser_Add_result(");
        sb.Append("Success: ");
        sb.Append(Success);
        sb.Append(")");
        return sb.ToString();
      }

    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class DemoUser_GetList_args : TBase
    {

      public DemoUser_GetList_args() {
      }

      public void Read (TProtocol iprot)
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }

      public void Write(TProtocol oprot) {
        TStruct struc = new TStruct("DemoUser_GetList_args");
        oprot.WriteStructBegin(struc);
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }

      public override string ToString() {
        StringBuilder sb = new StringBuilder("DemoUser_GetList_args(");
        sb.Append(")");
        return sb.ToString();
      }

    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class DemoUser_GetList_result : TBase
    {
      private List<DemoUser> _success;

      public List<DemoUser> Success
      {
        get
        {
          return _success;
        }
        set
        {
          __isset.success = true;
          this._success = value;
        }
      }


      public Isset __isset;
      #if !SILVERLIGHT
      [Serializable]
      #endif
      public struct Isset {
        public bool success;
      }

      public DemoUser_GetList_result() {
      }

      public void Read (TProtocol iprot)
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 0:
              if (field.Type == TType.List) {
                {
                  Success = new List<DemoUser>();
                  TList _list9 = iprot.ReadListBegin();
                  for( int _i10 = 0; _i10 < _list9.Count; ++_i10)
                  {
                    DemoUser _elem11 = new DemoUser();
                    _elem11 = new DemoUser();
                    _elem11.Read(iprot);
                    Success.Add(_elem11);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }

      public void Write(TProtocol oprot) {
        TStruct struc = new TStruct("DemoUser_GetList_result");
        oprot.WriteStructBegin(struc);
        TField field = new TField();

        if (this.__isset.success) {
          if (Success != null) {
            field.Name = "Success";
            field.Type = TType.List;
            field.ID = 0;
            oprot.WriteFieldBegin(field);
            {
              oprot.WriteListBegin(new TList(TType.Struct, Success.Count));
              foreach (DemoUser _iter12 in Success)
              {
                _iter12.Write(oprot);
              }
              oprot.WriteListEnd();
            }
            oprot.WriteFieldEnd();
          }
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }

      public override string ToString() {
        StringBuilder sb = new StringBuilder("DemoUser_GetList_result(");
        sb.Append("Success: ");
        sb.Append(Success);
        sb.Append(")");
        return sb.ToString();
      }

    }

  }
}
